// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'firebase_options.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28r34vVziRmgUPpgLoh1fhVJ7Dckc-Hk',
    appId: '1:992169374892:web:0b4e6d73cfd74594b21b09',
    messagingSenderId: '992169374892',
    projectId: 'my-diary-life',
    authDomain: 'my-diary-life.firebaseapp.com',
    storageBucket: 'my-diary-life.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BXnBxFnkgVoNb6WdaM5pSJG0X-0BNd8',
    appId: '1:992169374892:android:1116c3ae10973bffb21b09',
    messagingSenderId: '992169374892',
    projectId: 'my-diary-life',
    storageBucket: 'my-diary-life.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtLEjRjyuZp6z9NdayUciucmUOfuxMx00',
    appId: '1:992169374892:ios:f5b66f6e8413afcbb21b09',
    messagingSenderId: '992169374892',
    projectId: 'my-diary-life',
    storageBucket: 'my-diary-life.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28r34vVziRmgUPpgLoh1fhVJ7Dckc-Hk',
    appId: '1:992169374892:web:3eff65ea83e4f4b6b21b09',
    messagingSenderId: '992169374892',
    projectId: 'my-diary-life',
    authDomain: 'my-diary-life.firebaseapp.com',
    storageBucket: 'my-diary-life.firebasestorage.app',
  );
}
